after "development:sections" do
  puts 'seeding Students'

  # want more? http://www.mockaroo.com/
  user_attributes =[
    {first_name:"Jerry",last_name:"Russell"},
    {first_name:"Catherine",last_name:"Allen"},
    {first_name:"Sandra",last_name:"Jackson"},
    {first_name:"Charles",last_name:"Lawrence"},
    {first_name:"Patrick",last_name:"Gibson"},
    {first_name:"Sandra",last_name:"Howell"},
    {first_name:"Debra",last_name:"Knight"},
    {first_name:"Bobby",last_name:"Johnston"},
    {first_name:"Doris",last_name:"Collins"},
    {first_name:"Joshua",last_name:"Ramirez"},
    {first_name:"Roy",last_name:"Adams"},
    {first_name:"Willie",last_name:"Bryant"},
    {first_name:"Harold",last_name:"Matthews"},
    {first_name:"Mark",last_name:"Spencer"},
    {first_name:"Martha",last_name:"Welch"},
    {first_name:"Kenneth",last_name:"Cox"},
    {first_name:"Carl",last_name:"Burke"},
    {first_name:"Christina",last_name:"Chapman"},
    {first_name:"Jesse",last_name:"Thomas"},
    {first_name:"Sharon",last_name:"Howell"},
    {first_name:"George",last_name:"Duncan"},
    {first_name:"Janet",last_name:"Castillo"},
    {first_name:"Andrea",last_name:"Hall"},
    {first_name:"Nicole",last_name:"Gardner"},
    {first_name:"Maria",last_name:"Wells"},
    {first_name:"Christina",last_name:"Crawford"},
    {first_name:"Walter",last_name:"Simmons"},
    {first_name:"Louise",last_name:"Wallace"},
    {first_name:"Martin",last_name:"Nguyen"},
    {first_name:"Wayne",last_name:"Burton"},
    {first_name:"Randy",last_name:"Rodriguez"},
    {first_name:"Johnny",last_name:"Welch"},
    {first_name:"Annie",last_name:"Hanson"},
    {first_name:"Pamela",last_name:"Bowman"},
    {first_name:"Martin",last_name:"Banks"},
    {first_name:"Ashley",last_name:"Berry"},
    {first_name:"Nicole",last_name:"Jacobs"},
    {first_name:"Alan",last_name:"Stephens"},
    {first_name:"Joshua",last_name:"Collins"},
    {first_name:"Cynthia",last_name:"Williams"},
    {first_name:"Alice",last_name:"Powell"},
    {first_name:"Teresa",last_name:"Reyes"},
    {first_name:"Jane",last_name:"Butler"},
    {first_name:"Joan",last_name:"Sims"},
    {first_name:"Benjamin",last_name:"Wheeler"},
    {first_name:"Bruce",last_name:"Greene"},
    {first_name:"James",last_name:"Greene"},
    {first_name:"Linda",last_name:"Morgan"},
    {first_name:"Alice",last_name:"Gilbert"},
    {first_name:"John",last_name:"Schmidt"},
    {first_name:"Juan",last_name:"Arnold"},
    {first_name:"Fred",last_name:"Hicks"},
    {first_name:"Beverly",last_name:"Thomas"},
    {first_name:"Keith",last_name:"Mendoza"},
    {first_name:"Wanda",last_name:"Warren"},
    {first_name:"Nicole",last_name:"Wright"},
    {first_name:"Jeffrey",last_name:"Baker"},
    {first_name:"Ruth",last_name:"Griffin"},
    {first_name:"Janice",last_name:"Sims"},
    {first_name:"Deborah",last_name:"Nelson"},
    {first_name:"Heather",last_name:"Lawson"},
    {first_name:"Maria",last_name:"Ramirez"},
    {first_name:"Maria",last_name:"Payne"},
    {first_name:"Jimmy",last_name:"Armstrong"},
    {first_name:"Jack",last_name:"Johnson"},
    {first_name:"Johnny",last_name:"George"},
    {first_name:"Cheryl",last_name:"Boyd"},
    {first_name:"Nicholas",last_name:"Torres"},
    {first_name:"Peter",last_name:"Hart"},
    {first_name:"Arthur",last_name:"Kelly"},
    {first_name:"Lawrence",last_name:"Hudson"},
    {first_name:"Earl",last_name:"Ross"},
    {first_name:"Earl",last_name:"Young"},
    {first_name:"Joan",last_name:"Hawkins"},
    {first_name:"Deborah",last_name:"Alvarez"},
    {first_name:"Philip",last_name:"James"},
    {first_name:"Johnny",last_name:"Reynolds"},
    {first_name:"Frank",last_name:"Murphy"},
    {first_name:"Joshua",last_name:"Hart"},
    {first_name:"Virginia",last_name:"Weaver"},
    {first_name:"Maria",last_name:"Thompson"},
    {first_name:"Randy",last_name:"Hill"},
    {first_name:"Helen",last_name:"Fernandez"},
    {first_name:"Christina",last_name:"Mason"},
    {first_name:"George",last_name:"Black"},
    {first_name:"Shawn",last_name:"Arnold"},
    {first_name:"Joe",last_name:"Robertson"},
    {first_name:"Patricia",last_name:"Morgan"},
    {first_name:"Susan",last_name:"Gomez"},
    {first_name:"Heather",last_name:"Richardson"},
    {first_name:"Julia",last_name:"Stone"},
    {first_name:"Juan",last_name:"Cunningham"},
    {first_name:"Paul",last_name:"Lynch"},
    {first_name:"Judith",last_name:"Rivera"},
    {first_name:"David",last_name:"Lawrence"},
    {first_name:"Matthew",last_name:"Sanders"},
    {first_name:"Frances",last_name:"Lane"},
    {first_name:"Mildred",last_name:"Stevens"},
    {first_name:"Juan",last_name:"Rogers"},
    {first_name:"Denise",last_name:"Stone"}
  ]


  user_attributes.each do |attributes|
    school_id = sprintf('%05d', rand.to_s[2..6].to_i)
    attributes.merge!(email: "dev.project.uno@gmail.com+#{school_id}@gmail.com", school_id: school_id )
    Student.create user_attributes: attributes
  end

  puts "done seeding students"
end
